config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
  
  resources :recipes
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 255 }
  validates :ingredient, presence: true, length: { maximum: 500 }
  validates :howto, presence: true, length: { maximum: 500 }
  
  
  
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    has_secure_password
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_many :recipes   
    
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_user_logged_in
     unless logged_in?
      redirect_to login_url
     end
    end
end    

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :require_user_logged_in
    before_action :correct_user, only: [:edit, :update, :destroy]
    
    
  def index
      @recipes = Recipe.all
  end

  def show
      @recipe = Recipe.find(params[:id])
  end

  def new
      @recipe = current_user.recipes.build
  end
  
    def create
      @recipe = current_user.recipes.build(recipe_params)
      
      if @recipe.save
          flash[:success] = 'レシピを登録しました。'
          redirect_to root_url
      else
          flash.now[:danger] = 'レシピは登録されませんでした。'
          render :new
      end 
    end      

  def edit
      @recipe = Recipe.find(params[:id])
  end

  def update
       #@recipe = correct_user.recipes.find(recipe_params)
      
      if @recipe.update(recipe_params)
          flash[:success] = 'レシピを更新しました。'
          redirect_to root_url
      else
          flash.now[:danger] = 'レシピが更新されませんでした'
         render :edit
      end     
  end

  def destroy
      #@recipe = correct_user.recipes.find(recipe_params)
      @recipe.destroy

      flash[:success] = 'レシピは正常に削除されました'
      #redirect_back(fallback_location: root_path)
      redirect_to root_url
  end

  
  private
  
  def recipe_params
    params.require(:recipe).permit(:title, :ingredient, :howto)
  end
  
  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    unless @recipe
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password) 
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end


 private

 def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
 end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-warning">
    <a class="navbar-brand" href="/">My Recipes</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to '登録者一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'レシピを投稿する', new_recipe_url(current_user), class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My Recipe', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '新規会員登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
    
  </nav>
</header>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div>
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/edit.html.erb
<div class="text-center">
<h1>レシピ編集ページ</h1>


<div class="row">
  <div class="col-sm-6 offset-sm-3">

   <%= form_with(model: @recipe, local: true) do |f| %>
     
     <%= f.label :title, 'タイトル' %>
     <%= f.text_field :title, class: "form-control" %>
     
  
     <%= f.label :ingredient, '材料' %>
     <%= f.text_area :ingredient, class: "form-control" %>
  
     <%= f.label :howto, '作り方' %>
     <%= f.text_area :howto, class: "form-control" %>
  

     <%= f.submit '投稿', class: 'btn btn-primary' %>
   <% end %>

   
   <%= link_to '一覧に戻る', root_url, class: 'btn btn-info'%>
  </div>
</div>
</div>

app/views/recipes/new.html.erb
<div class="text-center">
<h1>レシピ登録ページ</h1>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

   <%= form_with(model: @recipe, local: true) do |f| %>
     
     <%= f.label :title, 'タイトル' %>
     <%= f.text_field :title, class: "form-control" %>
     
  
     <%= f.label :ingredient, '材料' %>
     <%= f.text_area :ingredient, class: "form-control" %>
  
     <%= f.label :howto, '作り方' %>
     <%= f.text_area :howto, class: "form-control" %>
  

     <%= f.submit '投稿', class: 'btn btn-primary' %>
   <% end %>

   
   <%= link_to '一覧に戻る', recipes_path, class: 'btn btn-info'%>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">

<h1 class="text-center" ><%= @recipe.title %>のレシピ by <%= link_to @recipe.user.name, user_path(@recipe.user) %></h1>

<table class="table table-striped table-bordered">
            <tr>
                <td class="text-center">タイトル</td>
                <td class="text-center"><%= @recipe.title %></td>
            </tr>
            <tr>
                <td class="text-center">材料</td>
                <td class="text-center"><%= @recipe.ingredient %></td>
            </tr>
            <tr>
                <td class="text-center">作り方</td>
                <td class="text-center"><%= @recipe.howto %></td>
            </tr>
        </table>


<%= link_to '一覧に戻る', root_url, class: 'btn btn-info'%>
<% if current_user == @recipe.user %>
<%= link_to 'このレシピを編集する', edit_recipe_path(@recipe), class: 'btn btn-light'%>
<%= link_to 'このレシピを削除する', @recipe, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-dark'%>
<% end %>
　</div>
</div>

app/views/toppages/index.html.erb
<div class="text-center">
  <% if logged_in? %>
   <p>ようこそ<%= current_user.name %>さん！</p>
   <h1>みんなのレシピ一覧</h1>

 
   <% @recipes.each do |recipe| %>
     <li><%= link_to recipe.title,  recipe_path(recipe) %></li>
   <% end %>
 
</div>
 <% else %>
 <div class="center jumbotron">
   <div class="text-center">
     <h1>My Recipes</h1>
     <h2>料理レシピをシェアしよう！</h2>
     <%= link_to '新規会員登録はこちら', signup_path %>
   </div>
 </div>
 <% end %>

app/views/users/_users.html.erb
<div class="text-center">

  <% if users.any? %>
   <% users.each do |user| %>
   <li><%= link_to user.name, user_path(user) %></li>
   <% end %>
   <%= paginate users %> 
  <% end %>
　

</div>

app/views/users/index.html.erb
<div class="text-center">
  <h1>登録者一覧</h1>
  
  <li><%= render 'users', users: @users %></li>
  
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規会員登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
     <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'お名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %>のレシピ一覧</h1>
    <% @user.recipes.all.each do |user_recipe| %>
    　<li><%= link_to user_recipe.title, recipe_url(user_recipe) %></li>
  　<% end %>
</div>